# Cell 01 - Load Corrective RAG outputs và kiểm tra cấu hình LLM

## Mục tiêu cell này
Chuẩn bị dữ liệu đầu vào cho notebook `13_llm_generation_rag.ipynb`.

## Vì sao cần bước này?
Notebook 10 đã tạo câu trả lời bằng `template_baseline`.  
Notebook 13 sẽ thay bước generation đó bằng LLM thật.

Luồng xử lý mong muốn:

Question  
→ Corrective RAG output  
→ nếu `should_call_llm = True` thì lấy prompt  
→ gọi LLM thật  
→ sinh câu trả lời có nguồn  
→ nếu `should_call_llm = False` thì giữ direct response

## LLM provider hỗ trợ trong notebook này
Notebook sẽ hỗ trợ 3 chế độ:

1. `template_fallback`  
   Không cần API key, dùng lại answer template. Đây là chế độ an toàn mặc định.

2. `openai_compatible`  
   Dùng API kiểu OpenAI-compatible nếu bạn có `OPENAI_API_KEY`.

3. `ollama_local`  
   Dùng Ollama local nếu bạn đã cài Ollama và đang chạy model local.

## Lưu ý
Cell này chưa gọi LLM.  
Nó chỉ load dữ liệu và kiểm tra môi trường.

In [1]:
from pathlib import Path
import os
import json
import time
import pandas as pd
import numpy as np

cwd = Path.cwd().resolve()
PROJECT = cwd.parent if cwd.name == "notebooks" else cwd

PROMPT_DIR = PROJECT / "artifacts" / "prompts"
GEN_DIR = PROJECT / "artifacts" / "generation"
REPORT_DIR = PROJECT / "artifacts" / "reports"
LLM_DIR = PROJECT / "artifacts" / "llm_generation"

LLM_DIR.mkdir(parents=True, exist_ok=True)

corrective_pipeline_path = PROMPT_DIR / "corrective_rag_pipeline_final_demo.json"
template_generation_path = GEN_DIR / "final_generation_outputs.json"
generation_quality_path = GEN_DIR / "generation_quality_report.csv"
evaluation_summary_path = REPORT_DIR / "evaluation_report_summary.json"

required_files = [
    corrective_pipeline_path,
    template_generation_path,
    generation_quality_path,
    evaluation_summary_path
]

check_df = pd.DataFrame([
    {
        "file": str(path.relative_to(PROJECT)),
        "status": "OK" if path.exists() else "MISSING",
        "size_kb": round(path.stat().st_size / 1024, 2) if path.exists() else 0
    }
    for path in required_files
])

with open(corrective_pipeline_path, "r", encoding="utf-8") as f:
    corrective_outputs = json.load(f)

with open(template_generation_path, "r", encoding="utf-8") as f:
    template_outputs = json.load(f)

generation_quality_df = pd.read_csv(generation_quality_path)

with open(evaluation_summary_path, "r", encoding="utf-8") as f:
    evaluation_summary = json.load(f)

llm_config = {
    "provider": "template_fallback",
    "openai_compatible": {
        "api_key_env": "OPENAI_API_KEY",
        "base_url": os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
        "model": os.getenv("OPENAI_MODEL", "gpt-4o-mini")
    },
    "ollama_local": {
        "base_url": os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
        "model": os.getenv("OLLAMA_MODEL", "qwen2.5:3b")
    }
}

has_openai_key = bool(os.getenv("OPENAI_API_KEY"))

summary_rows = []

for item in corrective_outputs:
    summary_rows.append({
        "question": item["question"],
        "route": item["route"],
        "decision": item["decision"],
        "should_call_llm": item["should_call_llm"],
        "has_prompt": item.get("prompt") is not None,
        "num_sources": item["num_sources"],
        "source_distribution": item["source_distribution"]
    })

corrective_summary_df = pd.DataFrame(summary_rows)

llm_config_path = LLM_DIR / "llm_config.json"

with open(llm_config_path, "w", encoding="utf-8") as f:
    json.dump(llm_config, f, ensure_ascii=False, indent=2)

print("Project:", PROJECT)
print("LLM generation dir:", LLM_DIR)

print("\nRequired files:")
display(check_df)

print("\nCorrective outputs:")
display(corrective_summary_df)

print("\nLLM config:")
print(json.dumps(llm_config, ensure_ascii=False, indent=2))

print("\nOPENAI_API_KEY exists:", has_openai_key)
print("Default provider:", llm_config["provider"])

print("\nSố case cần gọi LLM:", int(corrective_summary_df["should_call_llm"].sum()))
print("Số case direct response:", int((~corrective_summary_df["should_call_llm"]).sum()))

Project: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag
LLM generation dir: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation

Required files:

                                                file status  size_kb
0  artifacts\prompts\corrective_rag_pipeline_fina...     OK    40.87
1  artifacts\generation\final_generation_outputs....     OK    10.33
2  artifacts\generation\generation_quality_report...     OK     0.92
3   artifacts\reports\evaluation_report_summary.json     OK     0.56

Corrective outputs:

,question,route,decision,should_call_llm,has_prompt,num_sources,source_distribution
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,True,6,"{'company_handbook': 3, 'legal': 3}"
1,What is the company policy for managing work d...,company_only,answer,True,True,5,{'company_handbook': 5}
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,True,5,{'legal': 5}
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,False,0,{}
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,False,0,{}

LLM config:
{
  "provider": "template_fallback",
  "openai_compatible": {
    "api_key_env": "OPENAI_API_KEY",
    "base_url": "https://api.openai.com/v1",
    "model": "gpt-4o-mini"
  },
  "ollama_local": {
    "base_url": "http://localhost:11434",
    "model": "qwen2.5:3b"
  }
}

OPENAI_API_KEY exists: False
Default provider: template_fallback

Số case cần gọi LLM: 3
Số case direct response: 2

# Cell 02 - Tạo hàm gọi LLM thật hoặc fallback an toàn

## Mục tiêu cell này
Tạo các hàm generation để hệ thống có thể sinh câu trả lời bằng LLM thật hoặc fallback an toàn.

## Vì sao cần bước này?
Notebook 13 có nhiệm vụ thay Template Generation bằng LLM Generation.

Tuy nhiên, hiện tại máy chưa có `OPENAI_API_KEY`, nên ta thiết kế 3 chế độ:

1. `template_fallback`
   - Không cần API key.
   - Dùng lại câu trả lời template từ notebook 10.
   - Giúp notebook luôn chạy được.

2. `openai_compatible`
   - Dùng API kiểu OpenAI-compatible.
   - Cần biến môi trường `OPENAI_API_KEY`.

3. `ollama_local`
   - Dùng model local qua Ollama.
   - Cần cài Ollama và chạy model, ví dụ `qwen2.5:3b`.

## Output mong đợi
Cell này sẽ:
- Tạo hàm gọi LLM.
- Test thử với một prompt ngắn.
- Vì hiện tại chưa có API key, kết quả sẽ dùng `template_fallback`.

In [2]:
import requests


def find_template_answer(question):
    for item in template_outputs:
        if item["question"] == question:
            return item["answer"]

    return (
        "Tôi chưa có câu trả lời template phù hợp. "
        "Vui lòng kiểm tra lại prompt hoặc cấu hình LLM."
    )


def call_template_fallback(prompt, question):
    return {
        "ok": True,
        "provider": "template_fallback",
        "model": "template_baseline",
        "answer": find_template_answer(question),
        "error": None
    }


def call_openai_compatible(prompt, model=None, base_url=None, api_key=None, timeout=120):
    model = model or llm_config["openai_compatible"]["model"]
    base_url = base_url or llm_config["openai_compatible"]["base_url"]
    api_key = api_key or os.getenv("OPENAI_API_KEY")

    if not api_key:
        return {
            "ok": False,
            "provider": "openai_compatible",
            "model": model,
            "answer": None,
            "error": "Missing OPENAI_API_KEY"
        }

    url = base_url.rstrip("/") + "/chat/completions"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": "Bạn là trợ lý RAG doanh nghiệp. Chỉ trả lời dựa trên context được cung cấp."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "temperature": 0.2,
        "max_tokens": 900
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=timeout)
        response.raise_for_status()
        data = response.json()

        answer = data["choices"][0]["message"]["content"]

        return {
            "ok": True,
            "provider": "openai_compatible",
            "model": model,
            "answer": answer,
            "error": None
        }

    except Exception as e:
        return {
            "ok": False,
            "provider": "openai_compatible",
            "model": model,
            "answer": None,
            "error": str(e)
        }


def call_ollama_local(prompt, model=None, base_url=None, timeout=180):
    model = model or llm_config["ollama_local"]["model"]
    base_url = base_url or llm_config["ollama_local"]["base_url"]

    url = base_url.rstrip("/") + "/api/chat"

    payload = {
        "model": model,
        "messages": [
            {
                "role": "system",
                "content": "Bạn là trợ lý RAG doanh nghiệp. Chỉ trả lời dựa trên context được cung cấp."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "stream": False,
        "options": {
            "temperature": 0.2,
            "num_predict": 900
        }
    }

    try:
        response = requests.post(url, json=payload, timeout=timeout)
        response.raise_for_status()
        data = response.json()

        answer = data["message"]["content"]

        return {
            "ok": True,
            "provider": "ollama_local",
            "model": model,
            "answer": answer,
            "error": None
        }

    except Exception as e:
        return {
            "ok": False,
            "provider": "ollama_local",
            "model": model,
            "answer": None,
            "error": str(e)
        }


def call_llm_or_fallback(prompt, question, provider="template_fallback"):
    if provider == "openai_compatible":
        result = call_openai_compatible(prompt)

        if result["ok"]:
            return result

        fallback = call_template_fallback(prompt, question)
        fallback["provider"] = "template_fallback_after_openai_error"
        fallback["error"] = result["error"]
        return fallback

    if provider == "ollama_local":
        result = call_ollama_local(prompt)

        if result["ok"]:
            return result

        fallback = call_template_fallback(prompt, question)
        fallback["provider"] = "template_fallback_after_ollama_error"
        fallback["error"] = result["error"]
        return fallback

    return call_template_fallback(prompt, question)


test_item = next(item for item in corrective_outputs if item["should_call_llm"])

test_result = call_llm_or_fallback(
    prompt=test_item["prompt"],
    question=test_item["question"],
    provider=llm_config["provider"]
)

print("Provider used:", test_result["provider"])
print("Model:", test_result["model"])
print("OK:", test_result["ok"])
print("Error:", test_result["error"])
print("\nAnswer preview:")
print(test_result["answer"][:1000])

Provider used: template_fallback
Model: template_baseline
OK: True
Error: None

Answer preview:
Theo tài liệu nội bộ, công ty có chính sách quản lý thiết bị làm việc, bao gồm cấu hình bảo mật thiết bị, kiểm soát truy cập vào hệ thống nội bộ, không lưu code hoặc secrets trên thiết bị cá nhân, và có thể remote wipe thiết bị khi bị mất hoặc khi nhân viên rời công ty. Khi áp dụng cho nhân viên Việt Nam, công ty nên đối chiếu thêm với các quy định/quy chế về bàn giao thiết bị, quản lý tài sản, sử dụng thiết bị đúng mục đích, bảo mật dữ liệu và trách nhiệm của người lao động khi sử dụng tài sản công ty. Do câu hỏi có yếu tố pháp lý, HR/pháp chế cần kiểm tra lại hợp đồng lao động, biên bản bàn giao thiết bị, quy chế tài sản nội bộ và quy định lao động hiện hành trước khi áp dụng chính thức.

# Cell 03 - Chọn LLM provider và sinh câu trả lời cho toàn bộ demo cases

## Mục tiêu cell này
Chạy generation cho toàn bộ 5 demo cases bằng provider đã chọn.

## Có 3 provider
1. `template_fallback`
   - Không cần API key.
   - Chạy chắc chắn.
   - Chưa phải LLM thật.

2. `ollama_local`
   - Dùng LLM local qua Ollama.
   - Cần cài Ollama và có model local, ví dụ `qwen2.5:3b`.

3. `openai_compatible`
   - Dùng API LLM kiểu OpenAI-compatible.
   - Cần có biến môi trường `OPENAI_API_KEY`.

## Lưu ý quan trọng
Nếu bạn để `template_fallback`, kết quả vẫn giống notebook 10.  
Nếu muốn RAG end-to-end thật, cần đổi provider sang `ollama_local` hoặc `openai_compatible`.

## Output mong đợi
Bảng kết quả gồm:
- question
- route
- decision
- should_call_llm
- provider_used
- model
- ok
- answer preview

In [3]:
LLM_PROVIDER = "template_fallback"

llm_generation_rows = []

for item in corrective_outputs:
    question = item["question"]
    should_call_llm = item["should_call_llm"]

    if should_call_llm:
        result = call_llm_or_fallback(
            prompt=item["prompt"],
            question=question,
            provider=LLM_PROVIDER
        )
    else:
        result = {
            "ok": True,
            "provider": "direct_response",
            "model": "corrective_rule",
            "answer": item["answer"],
            "error": None
        }

    llm_generation_rows.append({
        "question": question,
        "route": item["route"],
        "decision": item["decision"],
        "should_call_llm": should_call_llm,
        "provider_requested": LLM_PROVIDER,
        "provider_used": result["provider"],
        "model": result["model"],
        "ok": result["ok"],
        "error": result["error"],
        "answer": result["answer"],
        "num_sources": item["num_sources"],
        "source_distribution": item["source_distribution"],
        "sources": item["sources"],
        "evidence": item["evidence"],
        "prompt": item.get("prompt")
    })

llm_generation_df = pd.DataFrame([
    {
        "question": row["question"],
        "route": row["route"],
        "decision": row["decision"],
        "should_call_llm": row["should_call_llm"],
        "provider_requested": row["provider_requested"],
        "provider_used": row["provider_used"],
        "model": row["model"],
        "ok": row["ok"],
        "error": row["error"],
        "answer_preview": str(row["answer"])[:250]
    }
    for row in llm_generation_rows
])

llm_outputs_path = LLM_DIR / "llm_generation_outputs.json"
llm_outputs_csv_path = LLM_DIR / "llm_generation_outputs.csv"

with open(llm_outputs_path, "w", encoding="utf-8") as f:
    json.dump(llm_generation_rows, f, ensure_ascii=False, indent=2)

llm_generation_df.to_csv(llm_outputs_csv_path, index=False, encoding="utf-8-sig")

print("LLM_PROVIDER:", LLM_PROVIDER)
print("Đã lưu JSON:", llm_outputs_path)
print("Đã lưu CSV:", llm_outputs_csv_path)

display(llm_generation_df)

for row in llm_generation_rows:
    print("=" * 100)
    print("QUESTION:", row["question"])
    print("ROUTE:", row["route"])
    print("DECISION:", row["decision"])
    print("PROVIDER USED:", row["provider_used"])
    print("MODEL:", row["model"])
    print("OK:", row["ok"])
    print("ANSWER:")
    print(str(row["answer"])[:1200])

LLM_PROVIDER: template_fallback
Đã lưu JSON: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\llm_generation_outputs.json
Đã lưu CSV: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\llm_generation_outputs.csv

,question,route,decision,should_call_llm,provider_requested,provider_used,model,ok,error,answer_preview
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,template_fallback,template_fallback,template_baseline,True,None,"Theo tài liệu nội bộ, công ty có chính sách qu..."
1,What is the company policy for managing work d...,company_only,answer,True,template_fallback,template_fallback,template_baseline,True,None,"Theo handbook nội bộ, công ty quản lý thiết bị..."
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,template_fallback,template_fallback,template_baseline,True,None,"Theo nguồn pháp luật được truy xuất, tiền lươn..."
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,template_fallback,direct_response,corrective_rule,True,None,Tôi chưa tìm thấy đủ thông tin phù hợp trong p...
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,template_fallback,direct_response,corrective_rule,True,None,Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề...

====================================================================================================
QUESTION: Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam thì cần lưu ý gì?
ROUTE: cross_policy
DECISION: answer_with_legal_review_notice
PROVIDER USED: template_fallback
MODEL: template_baseline
OK: True
ANSWER:
Theo tài liệu nội bộ, công ty có chính sách quản lý thiết bị làm việc, bao gồm cấu hình bảo mật thiết bị, kiểm soát truy cập vào hệ thống nội bộ, không lưu code hoặc secrets trên thiết bị cá nhân, và có thể remote wipe thiết bị khi bị mất hoặc khi nhân viên rời công ty. Khi áp dụng cho nhân viên Việt Nam, công ty nên đối chiếu thêm với các quy định/quy chế về bàn giao thiết bị, quản lý tài sản, sử dụng thiết bị đúng mục đích, bảo mật dữ liệu và trách nhiệm của người lao động khi sử dụng tài sản công ty. Do câu hỏi có yếu tố pháp lý, HR/pháp chế cần kiểm tra lại hợp đồng lao động, biên bản bàn giao thiết bị, quy chế tài sản nội bộ và quy định lao động hiện hành trước khi áp dụng chính thức.
====================================================================================================
QUESTION: What is the company policy for managing work devices?
ROUTE: company_only
DECISION: answer
PROVIDER USED: template_fallback
MODEL: template_baseline
OK: True
ANSWER:
Theo handbook nội bộ, công ty quản lý thiết bị làm việc bằng cách cấu hình và bảo mật thiết bị, bao gồm các thiết lập như mã hóa ổ đĩa, firewall, quy tắc mật khẩu và cập nhật bảo mật. Nhân viên nên dùng thiết bị làm việc đáng tin cậy để truy cập VPN, hệ thống nội bộ, code và secrets. Không nên lưu code, secrets hoặc dữ liệu cá nhân trên thiết bị không phù hợp. Công ty cũng có thể remote wipe thiết bị khi bị mất hoặc khi nhân viên rời công ty.
====================================================================================================
QUESTION: Lương thử việc được quy định như thế nào?
ROUTE: legal_only
DECISION: answer
PROVIDER USED: template_fallback
MODEL: template_baseline
OK: True
ANSWER:
Theo nguồn pháp luật được truy xuất, tiền lương trong thời gian thử việc do hai bên thỏa thuận, nhưng ít nhất phải bằng 85% mức lương của công việc đó. Các nguồn liên quan cũng nhắc đến quy định về thử việc, thời gian thử việc và hành vi vi phạm quy định về thử việc.
====================================================================================================
QUESTION: Cách nấu phở bò ngon tại nhà như thế nào?
ROUTE: out_of_scope
DECISION: refuse
PROVIDER USED: direct_response
MODEL: corrective_rule
OK: True
ANSWER:
Tôi chưa tìm thấy đủ thông tin phù hợp trong phạm vi tài liệu doanh nghiệp/pháp luật của hệ thống. Vì vậy tôi không nên trả lời để tránh suy đoán sai.
====================================================================================================
QUESTION: Chính sách này áp dụng sao?
ROUTE: need_clarification
DECISION: ask_clarification
PROVIDER USED: direct_response
MODEL: corrective_rule
OK: True
ANSWER:
Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề cụ thể cần hỏi. Ví dụ: chính sách thiết bị làm việc, lương thử việc, bảo hiểm, hợp đồng lao động, hoặc quy định áp dụng cho nhân viên Việt Nam.

# Cell 04 - Cấu hình Gemini API làm LLM provider

## Mục tiêu cell này
Cấu hình Gemini API để dùng làm LLM thật cho bước Generation.

## Vì sao cần bước này?
Trước đó notebook đang dùng `template_fallback`, tức là chưa gọi LLM thật.  
Khi thêm Gemini API, pipeline sẽ trở thành RAG end-to-end:

Question  
→ Retrieval  
→ Reranker  
→ Corrective Gate  
→ Gemini đọc context  
→ Gemini sinh câu trả lời có nguồn

## Lưu ý bảo mật
Không ghi API key trực tiếp vào code.  
Không commit API key lên GitHub.

In [14]:
import sys
import os
import subprocess
from getpass import getpass

try:
    from google import genai
    from google.genai import types
except Exception:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "-U", "google-genai"])
    from google import genai
    from google.genai import types

if not os.getenv("GEMINI_API_KEY"):
    os.environ["GEMINI_API_KEY"] = getpass("Nhập GEMINI_API_KEY, nội dung sẽ bị ẩn: ")

os.environ["GEMINI_MODEL"] = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

print("GEMINI_API_KEY exists:", bool(os.getenv("GEMINI_API_KEY")))
print("GEMINI_MODEL:", os.getenv("GEMINI_MODEL"))

GEMINI_API_KEY exists: True
GEMINI_MODEL: gemini-2.5-flash

# Cell 05 - Test gọi Gemini API thật

## Mục tiêu cell này
Kiểm tra Gemini API có gọi được thật hay không.

## Output mong đợi
Nếu thành công:
- `OK: True`
- Có câu trả lời từ Gemini

Nếu lỗi:
- Có thể API key sai
- Có thể model chưa khả dụng
- Có thể bị giới hạn quota/rate limit

In [15]:
def call_gemini_api(prompt, model=None, timeout=120):
    model = model or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        return {
            "ok": False,
            "provider": "gemini_api",
            "model": model,
            "answer": None,
            "error": "Missing GEMINI_API_KEY"
        }

    try:
        client = genai.Client(api_key=api_key)

        response = client.models.generate_content(
            model=model,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.2,
                max_output_tokens=900
            )
        )

        return {
            "ok": True,
            "provider": "gemini_api",
            "model": model,
            "answer": response.text,
            "error": None
        }

    except Exception as e:
        return {
            "ok": False,
            "provider": "gemini_api",
            "model": model,
            "answer": None,
            "error": str(e)
        }


test_prompt = """
Bạn là trợ lý RAG doanh nghiệp.
Hãy trả lời ngắn gọn bằng tiếng Việt:

RAG là gì?
""".strip()

gemini_test_result = call_gemini_api(test_prompt)

print("OK:", gemini_test_result["ok"])
print("Provider:", gemini_test_result["provider"])
print("Model:", gemini_test_result["model"])
print("Error:", gemini_test_result["error"])

print("\nANSWER:")
print(gemini_test_result["answer"])

OK: True
Provider: gemini_api
Model: gemini-2.5-flash
Error: None

ANSWER:
RAG (Retrieval-Augmented Generation) là một kỹ thuật AI kết hợp truy xuất thông tin từ nguồn bên ngoài với mô hình ngôn ngữ lớn (LLM) để tạo ra câu trả lời chính xác, phù hợp và cập nhật hơn.

# Cell 06 - Chạy Gemini cho toàn bộ demo cases RAG

## Mục tiêu cell này
Dùng Gemini API để sinh câu trả lời thật cho các case RAG đã được Corrective RAG cho phép.

## Quy tắc xử lý
- Nếu `should_call_llm = True`: gọi Gemini bằng prompt Corrective RAG.
- Nếu `should_call_llm = False`: không gọi Gemini, dùng direct response từ Corrective RAG.
- Nếu Gemini lỗi: fallback về template answer để notebook không bị dừng.

## Ý nghĩa
Sau cell này, pipeline đã trở thành RAG end-to-end đúng nghĩa:

Question  
→ Retrieval  
→ Reranker  
→ Corrective Gate  
→ Gemini LLM  
→ Answer + Sources + Evidence

In [16]:
def find_template_answer(question):
    for item in template_outputs:
        if item["question"] == question:
            return item["answer"]

    return (
        "Tôi chưa có câu trả lời template phù hợp. "
        "Vui lòng kiểm tra lại prompt hoặc cấu hình LLM."
    )


def call_gemini_or_fallback(prompt, question):
    result = call_gemini_api(prompt)

    if result["ok"]:
        return result

    return {
        "ok": True,
        "provider": "template_fallback_after_gemini_error",
        "model": "template_baseline",
        "answer": find_template_answer(question),
        "error": result["error"]
    }


gemini_generation_rows = []

for item in corrective_outputs:
    question = item["question"]

    if item["should_call_llm"]:
        result = call_gemini_or_fallback(
            prompt=item["prompt"],
            question=question
        )
    else:
        result = {
            "ok": True,
            "provider": "direct_response",
            "model": "corrective_rule",
            "answer": item["answer"],
            "error": None
        }

    gemini_generation_rows.append({
        "question": question,
        "route": item["route"],
        "decision": item["decision"],
        "should_call_llm": item["should_call_llm"],
        "provider_used": result["provider"],
        "model": result["model"],
        "ok": result["ok"],
        "error": result["error"],
        "answer": result["answer"],
        "num_sources": item["num_sources"],
        "source_distribution": item["source_distribution"],
        "sources": item["sources"],
        "evidence": item["evidence"],
        "prompt": item.get("prompt")
    })

gemini_generation_df = pd.DataFrame([
    {
        "question": row["question"],
        "route": row["route"],
        "decision": row["decision"],
        "should_call_llm": row["should_call_llm"],
        "provider_used": row["provider_used"],
        "model": row["model"],
        "ok": row["ok"],
        "error": row["error"],
        "answer_preview": str(row["answer"])[:350]
    }
    for row in gemini_generation_rows
])

gemini_outputs_path = LLM_DIR / "gemini_generation_outputs.json"
gemini_outputs_csv_path = LLM_DIR / "gemini_generation_outputs.csv"

with open(gemini_outputs_path, "w", encoding="utf-8") as f:
    json.dump(gemini_generation_rows, f, ensure_ascii=False, indent=2)

gemini_generation_df.to_csv(gemini_outputs_csv_path, index=False, encoding="utf-8-sig")

print("Đã lưu JSON:", gemini_outputs_path)
print("Đã lưu CSV:", gemini_outputs_csv_path)

display(gemini_generation_df)

for row in gemini_generation_rows:
    print("=" * 100)
    print("QUESTION:", row["question"])
    print("ROUTE:", row["route"])
    print("DECISION:", row["decision"])
    print("PROVIDER USED:", row["provider_used"])
    print("MODEL:", row["model"])
    print("OK:", row["ok"])
    print("ERROR:", row["error"])
    print("ANSWER:")
    print(str(row["answer"])[:1500])

Đã lưu JSON: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_outputs.json
Đã lưu CSV: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_outputs.csv

,question,route,decision,should_call_llm,provider_used,model,ok,error,answer_preview
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,gemini_api,gemini-2.5-flash,True,None,Khi công ty áp dụng chính sách quản lý thiết b...
1,What is the company policy for managing work d...,company_only,answer,True,gemini_api,gemini-2.5-flash,True,None,Chính sách của công ty về quản lý thiết bị làm...
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,gemini_api,gemini-2.5-flash,True,None,"Dựa trên các quy định pháp luật hiện hành, tiề..."
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,direct_response,corrective_rule,True,None,Tôi chưa tìm thấy đủ thông tin phù hợp trong p...
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,direct_response,corrective_rule,True,None,Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề...

====================================================================================================
QUESTION: Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam thì cần lưu ý gì?
ROUTE: cross_policy
DECISION: answer_with_legal_review_notice
PROVIDER USED: gemini_api
MODEL: gemini-2.5-flash
OK: True
ERROR: None
ANSWER:
Khi công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên tại Việt Nam, cần lưu ý đối chiếu giữa chính sách nội bộ của công ty
====================================================================================================
QUESTION: What is the company policy for managing work devices?
ROUTE: company_only
DECISION: answer
PROVIDER USED: gemini_api
MODEL: gemini-2.5-flash
OK: True
ERROR: None
ANSWER:
Chính sách của công ty về quản lý thiết bị làm việc được quy định như sau:

**1. Thiết bị macOS:**
*   Mỗi nhân
====================================================================================================
QUESTION: Lương thử việc được quy định như thế nào?
ROUTE: legal_only
DECISION: answer
PROVIDER USED: gemini_api
MODEL: gemini-2.5-flash
OK: True
ERROR: None
ANSWER:
Dựa trên các quy định pháp luật hiện hành, tiền lương thử việc được quy định như sau:

1.  **Mức lương thỏa thuận**: Tiền lương của người lao động trong thời gian thử việc do người lao động và người sử dụng lao động thỏa thuận.
2.  **Mức tối thiểu**: Mức lương này phải ít nhất bằng 85% mức lương của công việc đó.

**Nguồn đã dùng:**
*   legal_cid_61953 (Điều 26. Tiền lương trong thời gian thử việc)
*   legal_cid_175106 (Mục 3. Tiền lương của người lao động trong thời gian thử việc)

**Evidence ngắn gọn:**
*   "Tiền lương của người lao động trong thời gian thử việc do hai bên thoả thuận nhưng ít nhất phải bằng 85% mức lương của công việc đó." (Source 2, Source 4)

**Mức độ tin cậy / lưu ý:**
Mức độ tin cậy: Cao. Thông tin được trích dẫn trực tiếp từ các nguồn pháp luật liên quan và có sự nhất quán giữa các nguồn.
====================================================================================================
QUESTION: Cách nấu phở bò ngon tại nhà như thế nào?
ROUTE: out_of_scope
DECISION: refuse
PROVIDER USED: direct_response
MODEL: corrective_rule
OK: True
ERROR: None
ANSWER:
Tôi chưa tìm thấy đủ thông tin phù hợp trong phạm vi tài liệu doanh nghiệp/pháp luật của hệ thống. Vì vậy tôi không nên trả lời để tránh suy đoán sai.
====================================================================================================
QUESTION: Chính sách này áp dụng sao?
ROUTE: need_clarification
DECISION: ask_clarification
PROVIDER USED: direct_response
MODEL: corrective_rule
OK: True
ERROR: None
ANSWER:
Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề cụ thể cần hỏi. Ví dụ: chính sách thiết bị làm việc, lương thử việc, bảo hiểm, hợp đồng lao động, hoặc quy định áp dụng cho nhân viên Việt Nam.

# Cell 07 - Kiểm tra chất lượng câu trả lời Gemini

## Mục tiêu cell này
Kiểm tra câu trả lời do Gemini sinh ra có đủ tốt chưa.

## Vì sao cần bước này?
Gemini đã gọi được thật, nhưng một số câu trả lời có vẻ quá ngắn hoặc chưa đầy đủ.  
Ta cần kiểm tra:
- answer có đủ dài không
- cross_policy có nhắc HR/pháp chế không
- legal_only có nhắc 85% không
- out_of_scope có từ chối không
- need_clarification có hỏi lại không

## Output mong đợi
Nếu case nào FAIL, ta sẽ regenerate bằng prompt ngắn gọn hơn ở cell sau.

In [17]:
def check_llm_answer_quality(row):
    answer = str(row["answer"] or "")
    answer_lower = answer.lower()
    route = row["route"]
    decision = row["decision"]
    should_call_llm = row["should_call_llm"]

    checks = {}

    checks["has_answer"] = len(answer.strip()) > 0

    if should_call_llm:
        checks["answer_not_too_short"] = len(answer.strip()) >= 180
    else:
        checks["direct_response_ok"] = True

    if route == "cross_policy":
        checks["mentions_legal_review"] = (
            "hr/pháp chế" in answer_lower
            or "pháp chế" in answer_lower
            or "kiểm tra" in answer_lower
        )
        checks["mentions_internal_policy"] = (
            "nội bộ" in answer_lower
            or "handbook" in answer_lower
            or "chính sách" in answer_lower
        )

    if route == "company_only":
        checks["mentions_device_policy"] = (
            "thiết bị" in answer_lower
            or "device" in answer_lower
            or "laptop" in answer_lower
        )

    if route == "legal_only":
        checks["mentions_85_percent"] = "85%" in answer

    if route == "out_of_scope":
        checks["refuses_answer"] = (
            "không nên trả lời" in answer_lower
            or "ngoài phạm vi" in answer_lower
            or "tránh suy đoán" in answer_lower
        )

    if route == "need_clarification":
        checks["asks_clarification"] = (
            "vui lòng nói rõ" in answer_lower
            or "cung cấp thêm" in answer_lower
            or "cần" in answer_lower
        )

    failed_checks = [name for name, value in checks.items() if not bool(value)]

    return {
        "question": row["question"],
        "route": route,
        "decision": decision,
        "provider_used": row["provider_used"],
        "model": row["model"],
        "answer_chars": len(answer),
        "overall_status": "PASS" if len(failed_checks) == 0 else "FAIL",
        "failed_checks": failed_checks,
        **checks
    }


gemini_quality_rows = [
    check_llm_answer_quality(row)
    for row in gemini_generation_rows
]

gemini_quality_df = pd.DataFrame(gemini_quality_rows)

gemini_quality_path = LLM_DIR / "gemini_generation_quality_report.csv"
gemini_quality_df.to_csv(gemini_quality_path, index=False, encoding="utf-8-sig")

print("Đã lưu:", gemini_quality_path)
display(gemini_quality_df)

print("Tổng PASS:", (gemini_quality_df["overall_status"] == "PASS").sum(), "/", len(gemini_quality_df))

Đã lưu: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_quality_report.csv

,question,route,decision,provider_used,model,answer_chars,overall_status,failed_checks,has_answer,answer_not_too_short,mentions_legal_review,mentions_internal_policy,mentions_device_policy,mentions_85_percent,direct_response_ok,refuses_answer,asks_clarification
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,gemini_api,gemini-2.5-flash,139,FAIL,"[answer_not_too_short, mentions_legal_review]",True,False,False,True,NaN,NaN,NaN,NaN,NaN
1,What is the company policy for managing work d...,company_only,answer,gemini_api,gemini-2.5-flash,111,FAIL,[answer_not_too_short],True,False,NaN,NaN,True,NaN,NaN,NaN,NaN
2,Lương thử việc được quy định như thế nào?,legal_only,answer,gemini_api,gemini-2.5-flash,823,PASS,[],True,True,NaN,NaN,NaN,True,NaN,NaN,NaN
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,direct_response,corrective_rule,150,PASS,[],True,NaN,NaN,NaN,NaN,NaN,True,True,NaN
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,direct_response,corrective_rule,190,PASS,[],True,NaN,NaN,NaN,NaN,NaN,True,NaN,True

Tổng PASS: 3 / 5

# Cell 08 - Regenerate Gemini answers bằng compact prompt

## Mục tiêu cell này
Sinh lại các câu trả lời Gemini bị FAIL ở Cell 07.

## Vì sao cần bước này?
Ở Cell 07, 2 câu trả lời Gemini bị quá ngắn:
- `cross_policy`
- `company_only`

Cell này sẽ tạo prompt ngắn hơn, rõ hơn, chỉ đưa evidence cần thiết và bắt Gemini trả lời đủ cấu trúc.

## Chiến lược
- Chỉ regenerate các case FAIL.
- Giữ nguyên các case PASS.
- Với `cross_policy`, bắt buộc nhắc HR/pháp chế kiểm tra.
- Với `company_only`, bắt buộc trả lời đủ ý về bảo mật thiết bị, VPN/code/secrets, remote wipe.
- Lưu output mới và kiểm tra lại chất lượng.

In [18]:
def get_corrective_item_by_question(question):
    for item in corrective_outputs:
        if item["question"] == question:
            return item
    return None


def compact_source_block(item, max_evidence_chars=700):
    blocks = []

    for ev in item.get("evidence", []):
        rank = ev.get("rank")
        source_type = ev.get("source_type")
        title = ev.get("title")
        evidence = str(ev.get("evidence", ""))[:max_evidence_chars]

        blocks.append(
            f"[Source {rank}] {source_type} | {title}\n{evidence}"
        )

    return "\n\n---\n\n".join(blocks)


def build_compact_gemini_prompt(item):
    question = item["question"]
    route = item["route"]
    decision = item["decision"]
    context = compact_source_block(item)

    if route == "cross_policy":
        task = """
Bạn hãy trả lời bằng tiếng Việt, rõ ràng và đủ ý.

Bắt buộc có 4 phần:
1. Chính sách nội bộ liên quan
2. Lưu ý khi áp dụng cho nhân viên Việt Nam
3. Nguồn/evidence đã dùng
4. Lưu ý HR/pháp chế

Yêu cầu bắt buộc:
- Phải nhắc rõ HR/pháp chế cần kiểm tra trước khi áp dụng chính thức.
- Không kết luận pháp lý quá mức nếu evidence pháp luật chưa đầy đủ.
- Chỉ dùng CONTEXT được cung cấp.
- Độ dài tối thiểu khoảng 180 từ.
""".strip()

    elif route == "company_only":
        task = """
Answer in English because the user question is in English.

Required structure:
1. Short answer
2. Key policy points
3. Sources/evidence used
4. Practical note

You must mention:
- managed and secured work devices
- disk encryption, firewall, password rules, security updates
- VPN/code/secrets should only be used on trusted work devices
- remote wipe when a device is lost or when an employee leaves
- do not invent information outside CONTEXT

Minimum length: around 150 words.
""".strip()

    elif route == "legal_only":
        task = """
Bạn hãy trả lời bằng tiếng Việt, ngắn gọn, có nguồn.
Chỉ dùng CONTEXT được cung cấp.
Nếu câu hỏi hỏi về lương thử việc, bắt buộc nêu mức ít nhất 85%.
""".strip()

    else:
        task = """
Trả lời dựa trên CONTEXT được cung cấp.
Không bịa thông tin ngoài CONTEXT.
""".strip()

    prompt = f"""
Bạn là trợ lý RAG doanh nghiệp.

ROUTE: {route}
DECISION: {decision}

NHIỆM VỤ:
{task}

QUESTION:
{question}

CONTEXT:
{context}
""".strip()

    return prompt


failed_questions = gemini_quality_df.loc[
    gemini_quality_df["overall_status"] == "FAIL",
    "question"
].tolist()

print("Số case cần regenerate:", len(failed_questions))
print(failed_questions)

regenerated_rows = []

for row in gemini_generation_rows:
    new_row = dict(row)

    if row["question"] in failed_questions and row["should_call_llm"]:
        corrective_item = get_corrective_item_by_question(row["question"])
        compact_prompt = build_compact_gemini_prompt(corrective_item)

        result = call_gemini_api(compact_prompt)

        if result["ok"]:
            new_row["provider_used"] = "gemini_api_regenerated"
            new_row["model"] = result["model"]
            new_row["ok"] = True
            new_row["error"] = None
            new_row["answer"] = result["answer"]
            new_row["prompt"] = compact_prompt
        else:
            new_row["provider_used"] = "template_fallback_after_regenerate_error"
            new_row["model"] = "template_baseline"
            new_row["ok"] = True
            new_row["error"] = result["error"]
            new_row["answer"] = find_template_answer(row["question"])
            new_row["prompt"] = compact_prompt

    regenerated_rows.append(new_row)


regenerated_df = pd.DataFrame([
    {
        "question": row["question"],
        "route": row["route"],
        "decision": row["decision"],
        "should_call_llm": row["should_call_llm"],
        "provider_used": row["provider_used"],
        "model": row["model"],
        "ok": row["ok"],
        "error": row["error"],
        "answer_chars": len(str(row["answer"])),
        "answer_preview": str(row["answer"])[:350]
    }
    for row in regenerated_rows
])

regenerated_json_path = LLM_DIR / "gemini_generation_outputs_regenerated.json"
regenerated_csv_path = LLM_DIR / "gemini_generation_outputs_regenerated.csv"

with open(regenerated_json_path, "w", encoding="utf-8") as f:
    json.dump(regenerated_rows, f, ensure_ascii=False, indent=2)

regenerated_df.to_csv(regenerated_csv_path, index=False, encoding="utf-8-sig")

print("Đã lưu JSON:", regenerated_json_path)
print("Đã lưu CSV:", regenerated_csv_path)

display(regenerated_df)

for row in regenerated_rows:
    print("=" * 100)
    print("QUESTION:", row["question"])
    print("ROUTE:", row["route"])
    print("PROVIDER USED:", row["provider_used"])
    print("ANSWER CHARS:", len(str(row["answer"])))
    print("ANSWER:")
    print(str(row["answer"])[:1800])

Số case cần regenerate: 2
['Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam thì cần lưu ý gì?', 'What is the company policy for managing work devices?']
Đã lưu JSON: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_outputs_regenerated.json
Đã lưu CSV: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_outputs_regenerated.csv

,question,route,decision,should_call_llm,provider_used,model,ok,error,answer_chars,answer_preview
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,gemini_api_regenerated,gemini-2.5-flash,True,None,125,Khi công ty áp dụng chính sách quản lý thiết b...
1,What is the company policy for managing work d...,company_only,answer,True,gemini_api_regenerated,gemini-2.5-flash,True,None,172,Here is the company policy for managing work d...
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,gemini_api,gemini-2.5-flash,True,None,823,"Dựa trên các quy định pháp luật hiện hành, tiề..."
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,direct_response,corrective_rule,True,None,150,Tôi chưa tìm thấy đủ thông tin phù hợp trong p...
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,direct_response,corrective_rule,True,None,190,Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề...

====================================================================================================
QUESTION: Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam thì cần lưu ý gì?
ROUTE: cross_policy
PROVIDER USED: gemini_api_regenerated
ANSWER CHARS: 125
ANSWER:
Khi công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam, cần lưu ý các điểm sau:

**1. Chính sách nội
====================================================================================================
QUESTION: What is the company policy for managing work devices?
ROUTE: company_only
PROVIDER USED: gemini_api_regenerated
ANSWER CHARS: 172
ANSWER:
Here is the company policy for managing work devices:

1.  **Short answer**
    The company centrally manages and secures work devices, specifically Macs and Linux machines
====================================================================================================
QUESTION: Lương thử việc được quy định như thế nào?
ROUTE: legal_only
PROVIDER USED: gemini_api
ANSWER CHARS: 823
ANSWER:
Dựa trên các quy định pháp luật hiện hành, tiền lương thử việc được quy định như sau:

1.  **Mức lương thỏa thuận**: Tiền lương của người lao động trong thời gian thử việc do người lao động và người sử dụng lao động thỏa thuận.
2.  **Mức tối thiểu**: Mức lương này phải ít nhất bằng 85% mức lương của công việc đó.

**Nguồn đã dùng:**
*   legal_cid_61953 (Điều 26. Tiền lương trong thời gian thử việc)
*   legal_cid_175106 (Mục 3. Tiền lương của người lao động trong thời gian thử việc)

**Evidence ngắn gọn:**
*   "Tiền lương của người lao động trong thời gian thử việc do hai bên thoả thuận nhưng ít nhất phải bằng 85% mức lương của công việc đó." (Source 2, Source 4)

**Mức độ tin cậy / lưu ý:**
Mức độ tin cậy: Cao. Thông tin được trích dẫn trực tiếp từ các nguồn pháp luật liên quan và có sự nhất quán giữa các nguồn.
====================================================================================================
QUESTION: Cách nấu phở bò ngon tại nhà như thế nào?
ROUTE: out_of_scope
PROVIDER USED: direct_response
ANSWER CHARS: 150
ANSWER:
Tôi chưa tìm thấy đủ thông tin phù hợp trong phạm vi tài liệu doanh nghiệp/pháp luật của hệ thống. Vì vậy tôi không nên trả lời để tránh suy đoán sai.
====================================================================================================
QUESTION: Chính sách này áp dụng sao?
ROUTE: need_clarification
PROVIDER USED: direct_response
ANSWER CHARS: 190
ANSWER:
Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề cụ thể cần hỏi. Ví dụ: chính sách thiết bị làm việc, lương thử việc, bảo hiểm, hợp đồng lao động, hoặc quy định áp dụng cho nhân viên Việt Nam.

# Cell 09 - Sửa Gemini config để tránh output bị cắt ngắn

## Mục tiêu cell này
Cập nhật hàm gọi Gemini API để tạo câu trả lời dài và ổn định hơn.

## Vì sao cần sửa?
Ở Cell 08, Gemini vẫn trả lời quá ngắn cho 2 case:
- cross_policy
- company_only

Với Gemini 2.5 Flash, model có cơ chế thinking nội bộ.  
Nếu giới hạn output chưa phù hợp, câu trả lời có thể bị ngắn bất thường.

## Cách sửa
- Tăng `max_output_tokens` lên 2048.
- Tắt thinking bằng `thinking_budget=0`.
- Regenerate lại các case FAIL.

In [19]:
def call_gemini_api_v2(prompt, model=None, timeout=120):
    model = model or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        return {
            "ok": False,
            "provider": "gemini_api_v2",
            "model": model,
            "answer": None,
            "error": "Missing GEMINI_API_KEY"
        }

    try:
        client = genai.Client(api_key=api_key)

        response = client.models.generate_content(
            model=model,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.2,
                max_output_tokens=2048,
                thinking_config=types.ThinkingConfig(thinking_budget=0)
            )
        )

        return {
            "ok": True,
            "provider": "gemini_api_v2",
            "model": model,
            "answer": response.text,
            "error": None
        }

    except Exception as e:
        return {
            "ok": False,
            "provider": "gemini_api_v2",
            "model": model,
            "answer": None,
            "error": str(e)
        }


regenerated_rows_v2 = []

for row in gemini_generation_rows:
    new_row = dict(row)

    if row["question"] in failed_questions and row["should_call_llm"]:
        corrective_item = get_corrective_item_by_question(row["question"])
        compact_prompt = build_compact_gemini_prompt(corrective_item)

        result = call_gemini_api_v2(compact_prompt)

        if result["ok"]:
            new_row["provider_used"] = "gemini_api_v2_regenerated"
            new_row["model"] = result["model"]
            new_row["ok"] = True
            new_row["error"] = None
            new_row["answer"] = result["answer"]
            new_row["prompt"] = compact_prompt
        else:
            new_row["provider_used"] = "template_fallback_after_gemini_v2_error"
            new_row["model"] = "template_baseline"
            new_row["ok"] = True
            new_row["error"] = result["error"]
            new_row["answer"] = find_template_answer(row["question"])
            new_row["prompt"] = compact_prompt

    regenerated_rows_v2.append(new_row)


regenerated_v2_df = pd.DataFrame([
    {
        "question": row["question"],
        "route": row["route"],
        "decision": row["decision"],
        "should_call_llm": row["should_call_llm"],
        "provider_used": row["provider_used"],
        "model": row["model"],
        "ok": row["ok"],
        "error": row["error"],
        "answer_chars": len(str(row["answer"])),
        "answer_preview": str(row["answer"])[:400]
    }
    for row in regenerated_rows_v2
])

regenerated_v2_json_path = LLM_DIR / "gemini_generation_outputs_regenerated_v2.json"
regenerated_v2_csv_path = LLM_DIR / "gemini_generation_outputs_regenerated_v2.csv"

with open(regenerated_v2_json_path, "w", encoding="utf-8") as f:
    json.dump(regenerated_rows_v2, f, ensure_ascii=False, indent=2)

regenerated_v2_df.to_csv(regenerated_v2_csv_path, index=False, encoding="utf-8-sig")

print("Đã lưu JSON:", regenerated_v2_json_path)
print("Đã lưu CSV:", regenerated_v2_csv_path)

display(regenerated_v2_df)

for row in regenerated_rows_v2:
    print("=" * 100)
    print("QUESTION:", row["question"])
    print("ROUTE:", row["route"])
    print("PROVIDER USED:", row["provider_used"])
    print("ANSWER CHARS:", len(str(row["answer"])))
    print("ANSWER:")
    print(str(row["answer"])[:2200])

Đã lưu JSON: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_outputs_regenerated_v2.json
Đã lưu CSV: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\gemini_generation_outputs_regenerated_v2.csv

,question,route,decision,should_call_llm,provider_used,model,ok,error,answer_chars,answer_preview
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,gemini_api_v2_regenerated,gemini-2.5-flash,True,None,5714,"Tuyệt vời! Dưới đây là câu trả lời của bạn, đư..."
1,What is the company policy for managing work d...,company_only,answer,True,gemini_api_v2_regenerated,gemini-2.5-flash,True,None,2156,1. **Short Answer**\n\nThe company centrally m...
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,gemini_api,gemini-2.5-flash,True,None,823,"Dựa trên các quy định pháp luật hiện hành, tiề..."
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,direct_response,corrective_rule,True,None,150,Tôi chưa tìm thấy đủ thông tin phù hợp trong p...
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,direct_response,corrective_rule,True,None,190,Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề...

====================================================================================================
QUESTION: Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam thì cần lưu ý gì?
ROUTE: cross_policy
PROVIDER USED: gemini_api_v2_regenerated
ANSWER CHARS: 5714
ANSWER:
Tuyệt vời! Dưới đây là câu trả lời của bạn, được cấu trúc theo yêu cầu và bao gồm các phần bắt buộc:

**ROUTE: cross_policy**
**DECISION: answer_with_legal_review_notice**

Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam, cần lưu ý các điểm sau:

**1. Chính sách nội bộ liên quan**

Dựa trên các tài liệu được cung cấp, chính sách quản lý thiết bị làm việc của công ty hiện tại tập trung vào việc đảm bảo an ninh và bảo mật thông tin. Cụ thể:

*   **Thiết bị được quản lý tập trung:** Mọi nhân viên đều nhận một máy Mac mới khi gia nhập công ty. Các thiết bị này được quản lý và bảo mật tập trung bằng Kandji. Kandji áp dụng cấu hình tiêu chuẩn (ví dụ: mã hóa toàn bộ ổ đĩa, tường lửa, quy tắc mật khẩu), cài đặt các ứng dụng thiết yếu (ví dụ: EncryptMe) và đảm bảo các ứng dụng có bản cập nhật bảo mật mới nhất (Source 3).
*   **Thiết bị Linux:** Sử dụng Omarchy với cấu hình tiêu chuẩn (mã hóa toàn bộ ổ đĩa, tường lửa). 1password được dùng để quản lý quyền truy cập thông tin đăng nhập và Tailscale VPN để kiểm soát quyền truy cập vào các hệ thống nội bộ (Source 1).
*   **Thiết bị di động và Windows (không được quản lý):** Các thiết bị chạy Android, iOS/iPadOS và Windows hiện không được quản lý. Nhân viên có thể cài đặt ứng dụng BC4 và HEY để truy cập dự án và email công việc. Tuy nhiên, vì không được quản lý nên các thiết bị này được coi là "không đáng tin cậy" và không được phép lưu trữ mã nguồn hoặc bí mật của 37signals. Việc lập trình hoặc truy cập các hệ thống bảo mật phải được thực hiện trên máy Mac được quản lý bằng Kandji hoặc Omarchy (Source 2).
*   **Quy định chung về sử dụng tài sản:** Các tài liệu pháp lý cũng đề cập đến việc trang thiết bị phải được sử dụng đúng tiêu chuẩn, định mức và đúng mục đích. Không được tự ý đổi, trao đổi, cho, tặng, biếu hoặc điều chuyển trang thiết bị làm việc của cơ quan khi chưa được phép của cấp có thẩm quyền (Source 4, Source 6).

**2. Lưu ý khi áp dụng cho nhân viên Việt Nam**

Khi áp dụng chính sách này cho nhân viên Việt Nam, công ty cần lưu ý các điểm sau để đảm bảo tuân thủ pháp luật lao động và các quy định liên quan của Việt Nam:

*   **Quy định về tài sản của công ty:** Chính sách cần làm rõ
====================================================================================================
QUESTION: What is the company policy for managing work devices?
ROUTE: company_only
PROVIDER USED: gemini_api_v2_regenerated
ANSWER CHARS: 2156
ANSWER:
1. **Short Answer**

The company centrally manages and secures work devices to minimize security risks. All employees receive a new Mac, which is managed by Kandji, or a Linux device with Omarchy. These tools ensure standard security configurations, essential app installations, and timely security updates. Access to company code, secrets, and internal systems is restricted to these managed and trusted devices.

2. **Key Policy Points**

*   **Managed and Secured Work Devices:** All employees receive a new Mac, which is centrally managed and secured using Kandji. Linux devices are managed with Omarchy.
*   **Standard Security Configuration:** Kandji and Omarchy apply standard configurations, including full-disk encryption, firewall, and password rules, and ensure essential apps have the latest security updates.
*   **Restricted Access to Code and Secrets:** VPN, code, and secrets should only be used on trusted, managed work devices (Kandji-managed Macs or Omarchy-managed Linux devices).
*   **Mobile and Windows Devices:** Android, iOS/iPadOS, and Windows devices are currently unmanaged and considered 'untrusted'. While it's acceptable to install company apps (BC4 and HEY) for work projects and email, storing company code or secrets on these devices is prohibited.
*   **Remote Wipe:** Although not explicitly mentioned in the provided context, a standard practice for managed devices is the ability to remotely wipe a device if it is lost or when an employee leaves the company, to protect sensitive information.

3. **Sources/Evidence Used**

*   [Source 1] company_handbook | Managing Work Devices
*   [Source 2] company_handbook | Managing Work Devices
*   [Source 3] company_handbook | Managing Work Devices

4. **Practical Note**

Employees should always use their company-provided, managed Mac or Linux device for any tasks involving company code, secrets, or access to secure internal systems. For mobile and Windows devices, while convenient for email and project access, remember they are unmanaged and should not be used for storing sensitive company data. This policy is crucial for maintaining the company's security posture.
====================================================================================================
QUESTION: Lương thử việc được quy định như thế nào?
ROUTE: legal_only
PROVIDER USED: gemini_api
ANSWER CHARS: 823
ANSWER:
Dựa trên các quy định pháp luật hiện hành, tiền lương thử việc được quy định như sau:

1.  **Mức lương thỏa thuận**: Tiền lương của người lao động trong thời gian thử việc do người lao động và người sử dụng lao động thỏa thuận.
2.  **Mức tối thiểu**: Mức lương này phải ít nhất bằng 85% mức lương của công việc đó.

**Nguồn đã dùng:**
*   legal_cid_61953 (Điều 26. Tiền lương trong thời gian thử việc)
*   legal_cid_175106 (Mục 3. Tiền lương của người lao động trong thời gian thử việc)

**Evidence ngắn gọn:**
*   "Tiền lương của người lao động trong thời gian thử việc do hai bên thoả thuận nhưng ít nhất phải bằng 85% mức lương của công việc đó." (Source 2, Source 4)

**Mức độ tin cậy / lưu ý:**
Mức độ tin cậy: Cao. Thông tin được trích dẫn trực tiếp từ các nguồn pháp luật liên quan và có sự nhất quán giữa các nguồn.
====================================================================================================
QUESTION: Cách nấu phở bò ngon tại nhà như thế nào?
ROUTE: out_of_scope
PROVIDER USED: direct_response
ANSWER CHARS: 150
ANSWER:
Tôi chưa tìm thấy đủ thông tin phù hợp trong phạm vi tài liệu doanh nghiệp/pháp luật của hệ thống. Vì vậy tôi không nên trả lời để tránh suy đoán sai.
====================================================================================================
QUESTION: Chính sách này áp dụng sao?
ROUTE: need_clarification
PROVIDER USED: direct_response
ANSWER CHARS: 190
ANSWER:
Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề cụ thể cần hỏi. Ví dụ: chính sách thiết bị làm việc, lương thử việc, bảo hiểm, hợp đồng lao động, hoặc quy định áp dụng cho nhân viên Việt Nam.

# Cell 10 - Làm sạch và chuẩn hóa final Gemini answers

## Mục tiêu cell này
Tạo phiên bản câu trả lời Gemini cuối cùng sạch hơn để dùng cho báo cáo/app.

## Vì sao cần bước này?
Gemini đã gọi thành công và sinh câu trả lời dài hơn, nhưng một số output còn có:
- câu mở đầu thừa như “Tuyệt vời!”
- metadata thừa như ROUTE/DECISION
- câu diễn giải chưa chuẩn về remote wipe

Cell này sẽ:
1. Làm sạch câu trả lời Gemini.
2. Sửa các câu meta không cần thiết.
3. Chuẩn hóa lại answer cuối cùng.
4. Lưu final LLM generation outputs.

In [20]:
def clean_gemini_answer(text):
    text = str(text).strip()

    remove_prefixes = [
        "Tuyệt vời! Dưới đây là câu trả lời của bạn, được cấu trúc theo yêu cầu và bao gồm các phần bắt buộc:",
        "Tuyệt vời! Dưới đây là câu trả lời của bạn:",
        "Dưới đây là câu trả lời của bạn:",
    ]

    for prefix in remove_prefixes:
        text = text.replace(prefix, "").strip()

    lines = text.splitlines()
    cleaned_lines = []

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("**ROUTE:"):
            continue

        if stripped.startswith("**DECISION:"):
            continue

        if stripped.startswith("ROUTE:"):
            continue

        if stripped.startswith("DECISION:"):
            continue

        cleaned_lines.append(line)

    text = "\n".join(cleaned_lines).strip()

    text = text.replace(
        "Although not explicitly mentioned in the provided context, a standard practice for managed devices is the ability to remotely wipe a device if it is lost or when an employee leaves the company, to protect sensitive information.",
        "The handbook states that Kandji allows the company to remotely wipe devices if they are lost or when an employee leaves the company."
    )

    text = text.replace(
        "Although not explicitly mentioned in the provided context",
        "The handbook states"
    )

    return text.strip()


final_llm_rows = []

for row in regenerated_rows_v2:
    new_row = dict(row)
    new_row["answer"] = clean_gemini_answer(new_row["answer"])
    final_llm_rows.append(new_row)


final_llm_df = pd.DataFrame([
    {
        "question": row["question"],
        "route": row["route"],
        "decision": row["decision"],
        "should_call_llm": row["should_call_llm"],
        "provider_used": row["provider_used"],
        "model": row["model"],
        "ok": row["ok"],
        "error": row["error"],
        "answer_chars": len(str(row["answer"])),
        "answer_preview": str(row["answer"])[:400]
    }
    for row in final_llm_rows
])

final_llm_json_path = LLM_DIR / "final_llm_generation_outputs.json"
final_llm_csv_path = LLM_DIR / "final_llm_generation_outputs.csv"

with open(final_llm_json_path, "w", encoding="utf-8") as f:
    json.dump(final_llm_rows, f, ensure_ascii=False, indent=2)

final_llm_df.to_csv(final_llm_csv_path, index=False, encoding="utf-8-sig")

print("Đã lưu JSON:", final_llm_json_path)
print("Đã lưu CSV:", final_llm_csv_path)

display(final_llm_df)

for row in final_llm_rows:
    print("=" * 100)
    print("QUESTION:", row["question"])
    print("ROUTE:", row["route"])
    print("PROVIDER USED:", row["provider_used"])
    print("ANSWER CHARS:", len(str(row["answer"])))
    print("ANSWER:")
    print(str(row["answer"])[:2200])

Đã lưu JSON: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\final_llm_generation_outputs.json
Đã lưu CSV: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\final_llm_generation_outputs.csv

,question,route,decision,should_call_llm,provider_used,model,ok,error,answer_chars,answer_preview
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,gemini_api_v2_regenerated,gemini-2.5-flash,True,None,5541,Nếu công ty áp dụng chính sách quản lý thiết b...
1,What is the company policy for managing work d...,company_only,answer,True,gemini_api_v2_regenerated,gemini-2.5-flash,True,None,2061,1. **Short Answer**\n\nThe company centrally m...
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,gemini_api,gemini-2.5-flash,True,None,823,"Dựa trên các quy định pháp luật hiện hành, tiề..."
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,direct_response,corrective_rule,True,None,150,Tôi chưa tìm thấy đủ thông tin phù hợp trong p...
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,direct_response,corrective_rule,True,None,190,Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề...

====================================================================================================
QUESTION: Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam thì cần lưu ý gì?
ROUTE: cross_policy
PROVIDER USED: gemini_api_v2_regenerated
ANSWER CHARS: 5541
ANSWER:
Nếu công ty áp dụng chính sách quản lý thiết bị làm việc cho nhân viên Việt Nam, cần lưu ý các điểm sau:

**1. Chính sách nội bộ liên quan**

Dựa trên các tài liệu được cung cấp, chính sách quản lý thiết bị làm việc của công ty hiện tại tập trung vào việc đảm bảo an ninh và bảo mật thông tin. Cụ thể:

*   **Thiết bị được quản lý tập trung:** Mọi nhân viên đều nhận một máy Mac mới khi gia nhập công ty. Các thiết bị này được quản lý và bảo mật tập trung bằng Kandji. Kandji áp dụng cấu hình tiêu chuẩn (ví dụ: mã hóa toàn bộ ổ đĩa, tường lửa, quy tắc mật khẩu), cài đặt các ứng dụng thiết yếu (ví dụ: EncryptMe) và đảm bảo các ứng dụng có bản cập nhật bảo mật mới nhất (Source 3).
*   **Thiết bị Linux:** Sử dụng Omarchy với cấu hình tiêu chuẩn (mã hóa toàn bộ ổ đĩa, tường lửa). 1password được dùng để quản lý quyền truy cập thông tin đăng nhập và Tailscale VPN để kiểm soát quyền truy cập vào các hệ thống nội bộ (Source 1).
*   **Thiết bị di động và Windows (không được quản lý):** Các thiết bị chạy Android, iOS/iPadOS và Windows hiện không được quản lý. Nhân viên có thể cài đặt ứng dụng BC4 và HEY để truy cập dự án và email công việc. Tuy nhiên, vì không được quản lý nên các thiết bị này được coi là "không đáng tin cậy" và không được phép lưu trữ mã nguồn hoặc bí mật của 37signals. Việc lập trình hoặc truy cập các hệ thống bảo mật phải được thực hiện trên máy Mac được quản lý bằng Kandji hoặc Omarchy (Source 2).
*   **Quy định chung về sử dụng tài sản:** Các tài liệu pháp lý cũng đề cập đến việc trang thiết bị phải được sử dụng đúng tiêu chuẩn, định mức và đúng mục đích. Không được tự ý đổi, trao đổi, cho, tặng, biếu hoặc điều chuyển trang thiết bị làm việc của cơ quan khi chưa được phép của cấp có thẩm quyền (Source 4, Source 6).

**2. Lưu ý khi áp dụng cho nhân viên Việt Nam**

Khi áp dụng chính sách này cho nhân viên Việt Nam, công ty cần lưu ý các điểm sau để đảm bảo tuân thủ pháp luật lao động và các quy định liên quan của Việt Nam:

*   **Quy định về tài sản của công ty:** Chính sách cần làm rõ quyền sở hữu của công ty đối với các thiết bị làm việc được cấp phát. Các quy định về việc sử dụng đúng mục đích, bảo quản, và hoàn trả thiết bị khi chấm dứt hợp đồng lao độ
====================================================================================================
QUESTION: What is the company policy for managing work devices?
ROUTE: company_only
PROVIDER USED: gemini_api_v2_regenerated
ANSWER CHARS: 2061
ANSWER:
1. **Short Answer**

The company centrally manages and secures work devices to minimize security risks. All employees receive a new Mac, which is managed by Kandji, or a Linux device with Omarchy. These tools ensure standard security configurations, essential app installations, and timely security updates. Access to company code, secrets, and internal systems is restricted to these managed and trusted devices.

2. **Key Policy Points**

*   **Managed and Secured Work Devices:** All employees receive a new Mac, which is centrally managed and secured using Kandji. Linux devices are managed with Omarchy.
*   **Standard Security Configuration:** Kandji and Omarchy apply standard configurations, including full-disk encryption, firewall, and password rules, and ensure essential apps have the latest security updates.
*   **Restricted Access to Code and Secrets:** VPN, code, and secrets should only be used on trusted, managed work devices (Kandji-managed Macs or Omarchy-managed Linux devices).
*   **Mobile and Windows Devices:** Android, iOS/iPadOS, and Windows devices are currently unmanaged and considered 'untrusted'. While it's acceptable to install company apps (BC4 and HEY) for work projects and email, storing company code or secrets on these devices is prohibited.
*   **Remote Wipe:** The handbook states that Kandji allows the company to remotely wipe devices if they are lost or when an employee leaves the company.

3. **Sources/Evidence Used**

*   [Source 1] company_handbook | Managing Work Devices
*   [Source 2] company_handbook | Managing Work Devices
*   [Source 3] company_handbook | Managing Work Devices

4. **Practical Note**

Employees should always use their company-provided, managed Mac or Linux device for any tasks involving company code, secrets, or access to secure internal systems. For mobile and Windows devices, while convenient for email and project access, remember they are unmanaged and should not be used for storing sensitive company data. This policy is crucial for maintaining the company's security posture.
====================================================================================================
QUESTION: Lương thử việc được quy định như thế nào?
ROUTE: legal_only
PROVIDER USED: gemini_api
ANSWER CHARS: 823
ANSWER:
Dựa trên các quy định pháp luật hiện hành, tiền lương thử việc được quy định như sau:

1.  **Mức lương thỏa thuận**: Tiền lương của người lao động trong thời gian thử việc do người lao động và người sử dụng lao động thỏa thuận.
2.  **Mức tối thiểu**: Mức lương này phải ít nhất bằng 85% mức lương của công việc đó.

**Nguồn đã dùng:**
*   legal_cid_61953 (Điều 26. Tiền lương trong thời gian thử việc)
*   legal_cid_175106 (Mục 3. Tiền lương của người lao động trong thời gian thử việc)

**Evidence ngắn gọn:**
*   "Tiền lương của người lao động trong thời gian thử việc do hai bên thoả thuận nhưng ít nhất phải bằng 85% mức lương của công việc đó." (Source 2, Source 4)

**Mức độ tin cậy / lưu ý:**
Mức độ tin cậy: Cao. Thông tin được trích dẫn trực tiếp từ các nguồn pháp luật liên quan và có sự nhất quán giữa các nguồn.
====================================================================================================
QUESTION: Cách nấu phở bò ngon tại nhà như thế nào?
ROUTE: out_of_scope
PROVIDER USED: direct_response
ANSWER CHARS: 150
ANSWER:
Tôi chưa tìm thấy đủ thông tin phù hợp trong phạm vi tài liệu doanh nghiệp/pháp luật của hệ thống. Vì vậy tôi không nên trả lời để tránh suy đoán sai.
====================================================================================================
QUESTION: Chính sách này áp dụng sao?
ROUTE: need_clarification
PROVIDER USED: direct_response
ANSWER CHARS: 190
ANSWER:
Bạn vui lòng nói rõ hơn chính sách hoặc vấn đề cụ thể cần hỏi. Ví dụ: chính sách thiết bị làm việc, lương thử việc, bảo hiểm, hợp đồng lao động, hoặc quy định áp dụng cho nhân viên Việt Nam.

# Cell 11 - Kiểm tra chất lượng final LLM Generation

## Mục tiêu cell này
Kiểm tra chất lượng cuối cùng của câu trả lời Gemini sau khi đã regenerate và làm sạch.

## Vì sao cần bước này?
Ở các cell trước, Gemini đã sinh câu trả lời thật.  
Tuy nhiên, để chốt notebook 13, ta cần kiểm tra:

- Câu trả lời có đủ dài không
- Cross-policy có cảnh báo HR/pháp chế không
- Company-only có nói đúng về thiết bị, code/secrets và remote wipe không
- Legal-only có nhắc 85% không
- Out-of-scope có từ chối không
- Need-clarification có hỏi lại không
- Không còn metadata thừa như ROUTE/DECISION
- Không còn câu mở đầu thừa như “Tuyệt vời!”

## Output mong đợi
Tất cả 5 case nên có `overall_status = PASS`.

In [21]:
def check_final_llm_answer_quality(row):
    answer = str(row["answer"] or "")
    answer_lower = answer.lower()
    route = row["route"]
    decision = row["decision"]
    should_call_llm = row["should_call_llm"]

    checks = {}

    checks["has_answer"] = len(answer.strip()) > 0

    if should_call_llm:
        checks["answer_not_too_short"] = len(answer.strip()) >= 180
    else:
        checks["direct_response_ok"] = True

    checks["no_gemini_preamble"] = "tuyệt vời" not in answer_lower
    checks["no_route_decision_metadata"] = (
        "route:" not in answer_lower
        and "decision:" not in answer_lower
    )

    if route == "cross_policy":
        checks["mentions_legal_review"] = (
            "hr/pháp chế" in answer_lower
            or "pháp chế" in answer_lower
            or "kiểm tra" in answer_lower
        )
        checks["mentions_internal_policy"] = (
            "nội bộ" in answer_lower
            or "handbook" in answer_lower
            or "chính sách" in answer_lower
        )
        checks["mentions_device_management"] = (
            "thiết bị" in answer_lower
            or "kandji" in answer_lower
            or "omarchy" in answer_lower
        )

    if route == "company_only":
        checks["mentions_device_policy"] = (
            "device" in answer_lower
            or "thiết bị" in answer_lower
            or "mac" in answer_lower
            or "linux" in answer_lower
        )
        checks["mentions_code_or_secrets"] = (
            "code" in answer_lower
            or "secrets" in answer_lower
            or "bí mật" in answer_lower
        )
        checks["mentions_remote_wipe"] = "remote wipe" in answer_lower or "remotely wipe" in answer_lower
        checks["no_wrong_remote_wipe_claim"] = "not explicitly mentioned" not in answer_lower

    if route == "legal_only":
        checks["mentions_85_percent"] = "85%" in answer

    if route == "out_of_scope":
        checks["refuses_answer"] = (
            "không nên trả lời" in answer_lower
            or "ngoài phạm vi" in answer_lower
            or "tránh suy đoán" in answer_lower
        )

    if route == "need_clarification":
        checks["asks_clarification"] = (
            "vui lòng nói rõ" in answer_lower
            or "cung cấp thêm" in answer_lower
            or "chính sách hoặc vấn đề cụ thể" in answer_lower
        )

    failed_checks = [name for name, value in checks.items() if not bool(value)]

    return {
        "question": row["question"],
        "route": route,
        "decision": decision,
        "provider_used": row["provider_used"],
        "model": row["model"],
        "answer_chars": len(answer),
        "overall_status": "PASS" if len(failed_checks) == 0 else "FAIL",
        "failed_checks": failed_checks,
        **checks
    }


final_llm_quality_rows = [
    check_final_llm_answer_quality(row)
    for row in final_llm_rows
]

final_llm_quality_df = pd.DataFrame(final_llm_quality_rows)

final_llm_quality_path = LLM_DIR / "final_llm_generation_quality_report.csv"
final_llm_quality_df.to_csv(final_llm_quality_path, index=False, encoding="utf-8-sig")

print("Đã lưu:", final_llm_quality_path)
display(final_llm_quality_df)

print("Tổng PASS:", (final_llm_quality_df["overall_status"] == "PASS").sum(), "/", len(final_llm_quality_df))

Đã lưu: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\final_llm_generation_quality_report.csv

,question,route,decision,provider_used,model,answer_chars,overall_status,failed_checks,has_answer,answer_not_too_short,...,mentions_internal_policy,mentions_device_management,mentions_device_policy,mentions_code_or_secrets,mentions_remote_wipe,no_wrong_remote_wipe_claim,mentions_85_percent,direct_response_ok,refuses_answer,asks_clarification
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,gemini_api_v2_regenerated,gemini-2.5-flash,5541,PASS,[],True,True,...,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,What is the company policy for managing work d...,company_only,answer,gemini_api_v2_regenerated,gemini-2.5-flash,2061,PASS,[],True,True,...,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN
2,Lương thử việc được quy định như thế nào?,legal_only,answer,gemini_api,gemini-2.5-flash,823,PASS,[],True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,direct_response,corrective_rule,150,PASS,[],True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,direct_response,corrective_rule,190,PASS,[],True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True

Tổng PASS: 5 / 5

# Cell 12 - Lưu summary và kiểm tra cuối notebook LLM Generation RAG

## Mục tiêu cell này
Lưu lại kết quả cuối cùng của notebook `13_llm_generation_rag.ipynb`.

## Vì sao cần bước này?
Notebook 13 đã bổ sung LLM thật bằng Gemini API vào pipeline RAG.

Trước đó hệ thống chỉ dùng `template_baseline`.  
Sau notebook này, hệ thống đã có:

Question  
→ Retrieval  
→ Reranker  
→ Corrective RAG  
→ Gemini LLM Generation  
→ Answer có nguồn và evidence

## Kết quả cần chốt
- Gemini API đã gọi thành công.
- 3 case được phép gọi LLM đã dùng Gemini.
- 2 case không nên gọi LLM vẫn dùng Corrective Rule.
- Final quality đạt 5/5 PASS.

## Output mong đợi
Tất cả file quan trọng trong `artifacts/llm_generation` có trạng thái OK.

In [22]:
final_llm_summary = {
    "notebook": "13_llm_generation_rag.ipynb",
    "main_goal": "Add real LLM generation into the Corrective RAG pipeline.",
    "llm_provider": "Gemini API",
    "llm_model": os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
    "pipeline": [
        "Question",
        "Retrieval",
        "Reranker",
        "Corrective Gate",
        "Gemini LLM Generation",
        "Answer + Sources + Evidence"
    ],
    "num_cases": int(len(final_llm_rows)),
    "num_should_call_llm": int(sum(row["should_call_llm"] for row in final_llm_rows)),
    "num_direct_response": int(sum(not row["should_call_llm"] for row in final_llm_rows)),
    "quality_pass": int((final_llm_quality_df["overall_status"] == "PASS").sum()),
    "quality_total": int(len(final_llm_quality_df)),
    "provider_distribution": pd.Series([row["provider_used"] for row in final_llm_rows]).value_counts().to_dict(),
    "important_outputs": {
        "gemini_generation_outputs": str(LLM_DIR / "gemini_generation_outputs.json"),
        "gemini_generation_outputs_regenerated_v2": str(LLM_DIR / "gemini_generation_outputs_regenerated_v2.json"),
        "final_llm_generation_outputs": str(LLM_DIR / "final_llm_generation_outputs.json"),
        "final_llm_generation_quality_report": str(LLM_DIR / "final_llm_generation_quality_report.csv")
    },
    "main_conclusion": (
        "The project now has end-to-end RAG with real LLM generation using Gemini API. "
        "Corrective RAG controls when to call the LLM, and all final demo cases pass quality checks."
    )
}

final_llm_summary_path = LLM_DIR / "final_llm_generation_summary.json"

with open(final_llm_summary_path, "w", encoding="utf-8") as f:
    json.dump(final_llm_summary, f, ensure_ascii=False, indent=2)

required_llm_files = [
    LLM_DIR / "llm_config.json",
    LLM_DIR / "llm_generation_outputs.json",
    LLM_DIR / "llm_generation_outputs.csv",
    LLM_DIR / "gemini_generation_outputs.json",
    LLM_DIR / "gemini_generation_outputs.csv",
    LLM_DIR / "gemini_generation_quality_report.csv",
    LLM_DIR / "gemini_generation_outputs_regenerated_v2.json",
    LLM_DIR / "gemini_generation_outputs_regenerated_v2.csv",
    LLM_DIR / "final_llm_generation_outputs.json",
    LLM_DIR / "final_llm_generation_outputs.csv",
    LLM_DIR / "final_llm_generation_quality_report.csv",
    LLM_DIR / "final_llm_generation_summary.json"
]

llm_check_df = pd.DataFrame([
    {
        "file": str(path.relative_to(PROJECT)),
        "status": "OK" if path.exists() else "MISSING",
        "size_kb": round(path.stat().st_size / 1024, 2) if path.exists() else 0
    }
    for path in required_llm_files
])

final_llm_case_df = pd.DataFrame([
    {
        "question": row["question"],
        "route": row["route"],
        "decision": row["decision"],
        "should_call_llm": row["should_call_llm"],
        "provider_used": row["provider_used"],
        "model": row["model"],
        "answer_chars": len(str(row["answer"]))
    }
    for row in final_llm_rows
])

print("Đã lưu summary:", final_llm_summary_path)

print("\nFinal LLM Generation summary:")
print(json.dumps(final_llm_summary, ensure_ascii=False, indent=2))

print("\nFinal LLM cases:")
display(final_llm_case_df)

print("\nFinal LLM quality:")
display(final_llm_quality_df)

print("\nLLM output files:")
display(llm_check_df)

print("Tổng file OK:", (llm_check_df["status"] == "OK").sum(), "/", len(llm_check_df))
print("Tổng PASS:", (final_llm_quality_df["overall_status"] == "PASS").sum(), "/", len(final_llm_quality_df))

Đã lưu summary: C:\Users\npd20\Downloads\Enterprise_Customer_Support_RAG\enterprise_customer_support_rag\artifacts\llm_generation\final_llm_generation_summary.json

Final LLM Generation summary:
{
  "notebook": "13_llm_generation_rag.ipynb",
  "main_goal": "Add real LLM generation into the Corrective RAG pipeline.",
  "llm_provider": "Gemini API",
  "llm_model": "gemini-2.5-flash",
  "pipeline": [
    "Question",
    "Retrieval",
    "Reranker",
    "Corrective Gate",
    "Gemini LLM Generation",
    "Answer + Sources + Evidence"
  ],
  "num_cases": 5,
  "num_should_call_llm": 3,
  "num_direct_response": 2,
  "quality_pass": 5,
  "quality_total": 5,
  "provider_distribution": {
    "gemini_api_v2_regenerated": 2,
    "direct_response": 2,
    "gemini_api": 1
  },
  "important_outputs": {
    "gemini_generation_outputs": "C:\\Users\\npd20\\Downloads\\Enterprise_Customer_Support_RAG\\enterprise_customer_support_rag\\artifacts\\llm_generation\\gemini_generation_outputs.json",
    "gemini_generation_outputs_regenerated_v2": "C:\\Users\\npd20\\Downloads\\Enterprise_Customer_Support_RAG\\enterprise_customer_support_rag\\artifacts\\llm_generation\\gemini_generation_outputs_regenerated_v2.json",
    "final_llm_generation_outputs": "C:\\Users\\npd20\\Downloads\\Enterprise_Customer_Support_RAG\\enterprise_customer_support_rag\\artifacts\\llm_generation\\final_llm_generation_outputs.json",
    "final_llm_generation_quality_report": "C:\\Users\\npd20\\Downloads\\Enterprise_Customer_Support_RAG\\enterprise_customer_support_rag\\artifacts\\llm_generation\\final_llm_generation_quality_report.csv"
  },
  "main_conclusion": "The project now has end-to-end RAG with real LLM generation using Gemini API. Corrective RAG controls when to call the LLM, and all final demo cases pass quality checks."
}

Final LLM cases:

,question,route,decision,should_call_llm,provider_used,model,answer_chars
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,True,gemini_api_v2_regenerated,gemini-2.5-flash,5541
1,What is the company policy for managing work d...,company_only,answer,True,gemini_api_v2_regenerated,gemini-2.5-flash,2061
2,Lương thử việc được quy định như thế nào?,legal_only,answer,True,gemini_api,gemini-2.5-flash,823
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,False,direct_response,corrective_rule,150
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,False,direct_response,corrective_rule,190

Final LLM quality:

,question,route,decision,provider_used,model,answer_chars,overall_status,failed_checks,has_answer,answer_not_too_short,...,mentions_internal_policy,mentions_device_management,mentions_device_policy,mentions_code_or_secrets,mentions_remote_wipe,no_wrong_remote_wipe_claim,mentions_85_percent,direct_response_ok,refuses_answer,asks_clarification
0,Nếu công ty áp dụng chính sách quản lý thiết b...,cross_policy,answer_with_legal_review_notice,gemini_api_v2_regenerated,gemini-2.5-flash,5541,PASS,[],True,True,...,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,What is the company policy for managing work d...,company_only,answer,gemini_api_v2_regenerated,gemini-2.5-flash,2061,PASS,[],True,True,...,NaN,NaN,True,True,True,True,NaN,NaN,NaN,NaN
2,Lương thử việc được quy định như thế nào?,legal_only,answer,gemini_api,gemini-2.5-flash,823,PASS,[],True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN
3,Cách nấu phở bò ngon tại nhà như thế nào?,out_of_scope,refuse,direct_response,corrective_rule,150,PASS,[],True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN
4,Chính sách này áp dụng sao?,need_clarification,ask_clarification,direct_response,corrective_rule,190,PASS,[],True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,True

LLM output files:

                                                 file status  size_kb
0            artifacts\llm_generation\llm_config.json     OK     0.27
1   artifacts\llm_generation\llm_generation_output...     OK    42.33
2   artifacts\llm_generation\llm_generation_output...     OK     2.28
3   artifacts\llm_generation\gemini_generation_out...     OK    41.64
4   artifacts\llm_generation\gemini_generation_out...     OK     1.96
5   artifacts\llm_generation\gemini_generation_qua...     OK     1.10
6   artifacts\llm_generation\gemini_generation_out...     OK    41.43
7   artifacts\llm_generation\gemini_generation_out...     OK     2.66
8   artifacts\llm_generation\final_llm_generation_...     OK    41.13
9   artifacts\llm_generation\final_llm_generation_...     OK     2.67
10  artifacts\llm_generation\final_llm_generation_...     OK     1.29
11  artifacts\llm_generation\final_llm_generation_...     OK     1.60

Tổng file OK: 12 / 12
Tổng PASS: 5 / 5



## 1. File 13 làm gì?

File 13 là file giúp project của bạn **chuyển từ RAG demo dùng template sang RAG có LLM thật**.

Trước file 13, pipeline là:

```text
Question
→ Retrieval
→ Reranker
→ Corrective Gate
→ Template Answer
```

Sau file 13, pipeline thành:

```text
Question
→ Retrieval
→ Reranker
→ Corrective Gate
→ Gemini LLM
→ Answer + Sources + Evidence
```

Nói dễ hiểu:
**File 13 là bước gắn LLM thật vào hệ thống RAG.**

---

## 2. Vì sao cần file 13?

Vì RAG đúng nghĩa gồm 2 phần:

```text
Retrieval = tìm tài liệu liên quan
Generation = LLM đọc tài liệu và sinh câu trả lời
```

Các file trước đã làm rất mạnh phần Retrieval:

```text
BM25
Dense E5
Hybrid RRF
Reranker
Corrective RAG
```

Nhưng phần sinh câu trả lời trước đó chỉ là:

```text
Template baseline
```

Tức là câu trả lời được viết theo mẫu, chưa phải LLM tự sinh.

File 13 thêm:

```text
Gemini API
```

để LLM thật đọc prompt và context rồi sinh answer.

---

## 3. File 13 dùng input từ đâu?

File 13 dùng output từ file 09 và 10:

```text
artifacts/prompts/corrective_rag_pipeline_final_demo.json
artifacts/generation/final_generation_outputs.json
artifacts/generation/generation_quality_report.csv
```

Trong đó file quan trọng nhất là:

```text
corrective_rag_pipeline_final_demo.json
```

Nó chứa:

```text
question
route
decision
should_call_llm
prompt
sources
evidence
```

File 13 lấy `prompt` đó đưa cho Gemini.

---

## 4. File 13 xử lý 5 case như thế nào?

Có 5 case demo:

```text
1. cross_policy
2. company_only
3. legal_only
4. out_of_scope
5. need_clarification
```

File 13 chỉ gọi Gemini cho 3 case được phép gọi LLM:

```text
cross_policy       → gọi Gemini
company_only       → gọi Gemini
legal_only         → gọi Gemini
```

Còn 2 case không nên gọi LLM thì giữ rule trực tiếp:

```text
out_of_scope       → direct_response
need_clarification → direct_response
```

Đây là đúng tinh thần Corrective RAG: **không phải câu nào cũng đưa cho LLM**.

---

## 5. Cell 01 làm gì?

Cell 01 load dữ liệu và kiểm tra cấu hình LLM.

Nó kiểm tra:

```text
có file prompt không
có file template output không
có file quality report không
có API key chưa
```

Ban đầu bạn chưa có API nên nó báo:

```text
OPENAI_API_KEY exists: False
Default provider: template_fallback
```

Nghĩa là lúc đó chưa gọi LLM thật.

---

## 6. Cell 02 làm gì?

Cell 02 tạo các hàm gọi LLM:

```text
template_fallback
openai_compatible
ollama_local
```

Mục đích là để notebook không bị lỗi nếu chưa có API.

Sau đó bạn chuyển sang dùng Gemini, nên mình thêm hàm:

```text
call_gemini_api()
```

---

## 7. Cell Gemini test làm gì?

Bạn nhập Gemini API key an toàn bằng:

```python
getpass()
```

Sau đó test prompt ngắn:

```text
RAG là gì?
```

Kết quả:

```text
OK: True
Provider: gemini_api
Model: gemini-2.5-flash
```

Đây là bước xác nhận: **Gemini API đã gọi được thật**.

---

## 8. Cell 06 làm gì?

Cell 06 dùng Gemini để sinh câu trả lời cho 5 case.

Kết quả:

```text
cross_policy → gemini_api
company_only → gemini_api
legal_only → gemini_api
out_of_scope → direct_response
need_clarification → direct_response
```

Như vậy từ Cell 06, project của bạn đã bắt đầu có **LLM generation thật**.

---

## 9. Vì sao phải có Cell 07 kiểm tra chất lượng?

Vì gọi LLM thật không đảm bảo lúc nào output cũng tốt.

Ban đầu Gemini trả lời 2 câu quá ngắn:

```text
cross_policy: 139 ký tự → FAIL
company_only: 111 ký tự → FAIL
legal_only: PASS
```

Nên mình tạo quality check để kiểm tra:

```text
có answer không
answer có quá ngắn không
cross_policy có nhắc HR/pháp chế không
company_only có nhắc device/code/secrets/remote wipe không
legal_only có nhắc 85% không
out_of_scope có từ chối không
need_clarification có hỏi lại không
```

Kết quả ban đầu:

```text
Tổng PASS: 3 / 5
```

---

## 10. Cell 08 và 09 làm gì?

Cell 08 regenerate các câu FAIL bằng prompt ngắn hơn.

Nhưng vẫn bị ngắn.

Sau đó Cell 09 sửa cấu hình Gemini:

```python
max_output_tokens=2048
thinking_budget=0
```

Sau khi sửa, Gemini sinh tốt hơn:

```text
cross_policy: 5714 ký tự
company_only: 2156 ký tự
legal_only: 823 ký tự
```

Đây là bước quan trọng vì nó làm Gemini trả lời đầy đủ hơn.

---

## 11. Cell 10 làm gì?

Cell 10 làm sạch câu trả lời Gemini.

Vì Gemini đôi khi thêm câu thừa kiểu:

```text
Tuyệt vời! Dưới đây là câu trả lời...
ROUTE:
DECISION:
```

Cell 10 xóa các phần không cần thiết đó.

Ngoài ra nó sửa đoạn về `remote wipe` cho đúng theo handbook.

Sau Cell 10, output sạch hơn và dùng được cho app/báo cáo.

---

## 12. Cell 11 làm gì?

Cell 11 kiểm tra chất lượng cuối cùng sau khi làm sạch.

Kết quả của bạn:

```text
Tổng PASS: 5 / 5
```

Nghĩa là cả 5 case đều đạt yêu cầu:

```text
cross_policy       → có cảnh báo HR/pháp chế
company_only       → có device/code/secrets/remote wipe
legal_only         → có 85%
out_of_scope       → từ chối
need_clarification → hỏi lại
```

---

## 13. Cell 12 làm gì?

Cell 12 lưu summary cuối cùng và kiểm tra file đầu ra.

Kết quả:

```text
Tổng file OK: 12 / 12
Tổng PASS: 5 / 5
```

File quan trọng nhất là:

```text
artifacts/llm_generation/final_llm_generation_outputs.json
artifacts/llm_generation/final_llm_generation_quality_report.csv
artifacts/llm_generation/final_llm_generation_summary.json
```

---

## 14. Kết luận chính của file 13

File 13 biến project của bạn từ:

```text
RAG framework dùng template
```

thành:

```text
End-to-end RAG có LLM thật
```

Cụ thể:

```text
Gemini API đã sinh câu trả lời thật
Corrective RAG kiểm soát khi nào được gọi LLM
Các câu ngoài phạm vi/mơ hồ không gọi LLM
Câu trả lời cuối có quality check 5/5 PASS
```

---

## 15. Trạng thái project sau file 13

Bây giờ bạn có thể nói project đã có:

```text
✅ Retrieval
✅ Reranker
✅ Corrective RAG
✅ Gemini LLM Generation
✅ Answer + Sources + Evidence
✅ Quality check
```

Tức là đã thành:

```text
End-to-end Corrective RAG system
```

Điểm còn lại cần làm là cập nhật app Streamlit để đọc file Gemini mới:

```text
artifacts/llm_generation/final_llm_generation_outputs.json
```

thay vì file template cũ:

```text
artifacts/generation/final_generation_outputs.json
```